### ISSUE TITLE
Syphon.deserialize issue with checkboxes

### ISSUE THREAD

**Issue by diasjorge** [marionettejs/backbone.syphon#27] opened 2013-07-16 10:31 UTC
If you want to deserialize a model into multiple checkboxes it doesn't behave correctly.

For instance if you have a model like:

    {languages: ['en']}

and a form:

    <input name="languages[]" type="checkbox" value="en">
    <input name="languages[]" type="checkbox" value="fr">

Then syphon will check both checkboxes.

Our current solution is to only check the checkboxes that actually match on the value like:

    Backbone.Syphon.InputWriters.register("checkbox", function ($el, value) {
        if (_.isArray(value)) {
            if (_.contains(value, $el.val())) {
                $el.prop("checked", true)
            }
        } else {
           $el.prop("checked", value)
        }
    })

**Comment by rhubarbselleven** [comment] 2015-03-15 01:46
Hi @diasjorge I'm going to close this one as a duplicate of #25 

Thanks for your hint around the `InputWriter`

Ping @rogelio2k

**Closed by rhubarbselleven** 2015-03-15 01:46 UTC
Labels: bug, critical, enhancement
